#!/bin/sh

GW_PARENTAL_CONTROL_CDEV=gw_parental_control
echo "GW PARENTAL CONTROL mknod"
GW_PARENTAL_CONTROL_MAJOR=`grep ${GW_PARENTAL_CONTROL_CDEV} /proc/devices | cut -f 1 -d ' '`
echo "GW PARENTAL CONTROL ID $GW_PARENTAL_CONTROL_MAJOR"
mknod /dev/${GW_PARENTAL_CONTROL_CDEV}0 c $GW_PARENTAL_CONTROL_MAJOR 0
RET=$?
echo "GW PARENTAL CONTROL RET - $RET"

